service: tdsd

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: serverless
  region: eu-central-1

functions:
  currentDate:
    handler: handlers/date.endpoint
    events:
      - http:
          path: currentDate
          method: get
  currentTime:
    handler: handlers/time.endpoint
    events:
      - http:
          path: currentTime
          method: get

plugins:
  - serverless-mocha-plugin