'use strict';

// tests for currentDate
// Generated by serverless-mocha-plugin

const mod = require('../../handlers/date.js');
const mochaPlugin = require('serverless-mocha-plugin');
const sinon = require('sinon');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'endpoint' });
const datetimeService = require('./../../services/dateTimeService');

describe('currentDate', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  let sandbox;
  beforeEach(() => {
    sandbox = sinon.sandbox.create();
  });

  afterEach(() => {
    sandbox.restore();
  });

  it('should return current date', () => {
    const currentDate = 'Thu Apr 05 2017';
    sandbox.stub(datetimeService, 'getCurrentDate').returns(currentDate);
    return wrapped.run({}).then((response) => {
      const body = JSON.parse(response.body);
      expect(response.statusCode).to.be.equal(200);
      expect(body.message).to.equal(`Hello, the current date is ${currentDate}.`);
    });
  });
});
